In [1]:
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
actual_values =     [0, 1, 2, 3]
prediction_values = [0, 2, 1, 3]

accuracy = sum([a == p for a, p in zip(actual_values, prediction_values)]) / len(actual_values)
print(accuracy)

accuracy = accuracy_score(actual_values, prediction_values)
print(accuracy)

0.5


In [15]:
actual_values =     [0, 1, 0, 3, 0, 1, 2, 3]
prediction_values = [0, 2, 1, 3, 0, 2, 1, 3]

matrix = confusion_matrix(actual_values, prediction_values)
print(matrix)

# ___________ EXPLICACION ___________
# [2 1 0 0] ← fila de predicciones del numero 0
# [0 0 2 0] ← fila de predicciones del numero 1
# [0 1 0 0] ← fila de predicciones del numero 2
# [0 0 0 2] ← fila de predicciones del numero 3

# ___________ EJEMPLO FILA '0' ____________
#  1er valor: cuando el valor real era '0' se predijo 2 veces que era '0'
#  2do valor: cuando el valor real era '0' se predijo 1 vez que era '1'
#  3er valor: cuando el valor real era '0' se predijo 0 veces que era '2'
#  4to valor: cuando el valor real era '0' se predijo 0 veces que era '3'
# ___________________________________

[[2 1 0 0]
 [0 0 2 0]
 [0 1 0 0]
 [0 0 0 2]]


In [4]:
binary_true = [0, 0, 1, 1]
binary_pred = [0, 1, 0, 1]
tn, fp, fn, tp = confusion_matrix(binary_true, binary_pred).ravel()

print(f"True Negatives: {tn}, False Positives: {fp}, False Negatives: {fn}, True Positives: {tp}")

True Negatives: 1, False Positives: 1, False Negatives: 1, True Positives: 1
